# Dumb SSH node for cluster "two"
teleport:
  nodename: node-on-second-cluster
  auth_servers: ["two-auth"]
  auth_token: foo
  log:
    severity: DEBUG

ssh_service:
  enabled: yes
  labels:
      cluster: two
      role: dumb_node

proxy_service:
   enabled: no

auth_service:
  enabled: no
